### ISSUE TITLE
Error: Couldn't validate the request signature.

### ISSUE THREAD

**Issue by ydeshayes** [fyndme/messenger-bot-tester#1]
When I try to run the test I got this error:
```
Error: Couldn't validate the request signature.
    at BootBot._verifyRequestSignature (/Users/smile/Documents/node-js-getting-started/node_modules/bootbot/lib/BootBot.js:401:13)
    at /Users/smile/Documents/node-js-getting-started/node_modules/bootbot/node_modules/body-parser/lib/read.js:100:9
    at invokeCallback (/Users/smile/Documents/node-js-getting-started/node_modules/bootbot/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/Users/smile/Documents/node-js-getting-started/node_modules/bootbot/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/Users/smile/Documents/node-js-getting-started/node_modules/bootbot/node_modules/body-parser/node_modules/raw-body/index.js:307:7)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by adamjuhasz** [comment]
Whats the code look like?

**Comment by ydeshayes** [comment]
I try to test this simple bot:

```
var BootBot = require('bootbot');

console.log(process.env.NODE_ENV);

var bot = new BootBot({
  accessToken: 'EAAZA3k0NlQFsBAPZCR4HM7cfw2OsNpKzSCCXrzBjbrw5qOaNGcoZBXvhSKG6jmFBcZB4QQd2Yw26ZAqtfJJJRmR7qZCeSeG5K7dqFMaGZCgnonro2DJOJlJrdZBx65kqBmTJBqLoQ9joNySbvFjIjZAmLXQReoqG9ZBIQss9KFikq3bQZDZD',
  verifyToken: 'jffs5nGqvw6jWHJdXpXyaYjXUchRNHAK9NC38669pfsxgQQrXJAfB3bsWhdgMsLhwaAkRPML6tVur9xPwMKLmbmNz8yTD2d8rUphVNBzGUEf8GrpAJJxTZkQN7TV7BbcnKrVEgbdUvs5M6HLgpF273tumetS56KxYDAm958r5gzBuB77SnJKeWyMMveVCz6FRwFUpNZGshYMmHnu74y5syGQqsd68QdTm9ZW3wZK57GTLXdZwg5q796t3bM8J6rDBbTywuvNjVKvLK64ucWEyHwwpZRVNtchZ36j9z59GnsDHftGXTTk94zUE8ghC2HeXxMUJ3CPN2mZub56SbvhGJ4uNN8gYfBUCKKAv38r3wqR6KzaCJfbYTpLpxBV7Rbqm4kwXEhVJndSvawa4JuSMXNFHMPPLFhJYzQEud2kbAx5P3PtfjR4s2HxNGBHyNzBjDt27VCkMB7qxzUp6wpCqvL4e2KxuSetmjWQQFhjz5VjauAN3xYZtVusdgXsYxdEZP4Z5HxXSYgTsXD6U9vZgbygVAbEmnRtDKqV3Wca5PjvXTH78H895AwUYPQyygwkykjFSRTCJsm9pF4zbUWj4Q4kdEhzPXaMkTerMFxnsQfVkqtkB4xE2HwANdFcHQv8WA4vmhNSQUX8ep2N4nm9pnUPUNrMHXuRXksRQjnBV2bmYRt6kKra5jgbPfsWkeahSthV7QSgUdtpFYSKLxPhVsfLqm3pc4trhunJ8qsD6SRqyzuUV5k4jG7MjD7FhfszKT9trZZUtz49cZuhhNDzJJ78BdJKgDNTwtWvBqH9wB5NaVpyVUFqNBGXZQyjwgYVDaNetEvNm2K8apKZCxNV3mSPmbATsqFTGbJSGRPDscZtVaUHkKgjkNeb5tsCugevtrNBDnQMtsBuTBHQjxWTUgLH5NaJzs9VwHnnJUL5RXxnZEzEhJubpmVKnCpygA94LGdRwKrndVraULWCZbaGenG7EW3KCweK4CumTj8pKpp5fGjxG4y5fA9cjeFpkqLY',
  appSecret: 'e58c3539a0bdbca4be2f43b795c91fc7'
});

bot.on('message', (payload, chat) => {
  var text = payload.message.text;
  console.log(`The user said: ${text}`);
  chat.say(`Echo: ${text}`);
});

bot.start(process.env.PORT || 3000);
console.log(`Echo bot server running at port ${(process.env.PORT || 3000)}.`);
```
with your sample on mocha
```
const BotTester = require('messenger-bot-tester');

describe('bot test', function() {
  // webHookURL points to where yout bot is currently listening
  // choose a port for the test framework to listen on
  const testingPort = 3100;
  const webHookURL = 'http://localhost:' + 3000 + '/webhook';
  const tester = new BotTester.default(testingPort, webHookURL);

  before(function(){
    // start your own bot here or having it running already in the background
    // redirect all Facebook Requests to http://localhost:3100/v2.6 and not https://graph.facebook.com/v2.6
    return tester.startListening();
  });

  it('hi', function(){
    const theScript = new BotTester.Script('132', '20');
    theScript.sendTextMessage('hi');  //mock user sending "hi"
    theScript.expectTextResponses([   //either response is valid
      'Hey!', 
      'Welcome',
    ]);
    return tester.runScript(theScript);
  });
})
```

**Comment by adamjuhasz** [comment]
I assume 'bootbot' isn't sending the `chat.say(...)` to the tester, you'll need to set it to use the testing url in`webHookURL`, not sure how to do that in bootbot, you can also use [facebook-send-api](https://github.com/fyndme/facebook-send-api) and change the the graphURL in the constructor
